import os
from dotenv import load_dotenv

load_dotenv()
KSQLDB_URL = os.getenv("KSQLDB_URL")
KSQL_WS_URL = os.getenv("KSQL_WS_URL")

SCHEMA_TRADES = os.getenv("SCHEMA_TRADES")
SCHEMA_SP500_COMPANY_PROFILES = os.getenv("SCHEMA_SP500_COMPANY_PROFILES")
SCHEMA_STOCK_SYMBOLS = os.getenv("SCHEMA_STOCK_SYMBOLS")

SCHEMA_REGISTRY_URL = os.getenv("SCHEMA_REGISTRY_URL")
BOOTSTRAP_SERVERS = os.getenv("BOOTSTRAP_SERVERS")
KAFKA_TOPIC_COMPANY_PROFILES = os.getenv("KAFKA_TOPIC_COMPANY_PROFILES")
KAFKA_TOPIC_TRADES = os.getenv("KAFKA_TOPIC_TRADES")
KAFKA_TOPIC_SYMBOLS = os.getenv("KAFKA_TOPIC_SYMBOLS")


KAFKA_PARTITIONS = os.getenv("KAFKA_PARTITIONS")
KAFKA_REPLICATION_FACTOR = os.getenv("KAFKA_REPLICATION_FACTOR")
